### PR TITLE
Fix SyntaxError on Python 2

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by jaimebuelta** [comment]
Thanks!

**Comment by jayvdb** [comment]
Thank you.  This is now ready to put into production for my needs, waiting only on an official release.  https://gerrit.wikimedia.org/r/#/c/260909/

If there is anything you want done before the next release, especially relating to my changes, feel free to create a task and assign it to me to do.

**Comment by jaimebuelta** [comment]
Hey @jayvdb I've created a new release. It's available in PyPI. Version 1.0 already!

**Comment by jayvdb** [comment]
Install fails
https://integration.wikimedia.org/ci/job/tox-jessie/7727/console

**Comment by jaimebuelta** [comment]
I resubmitted it to PyPI (as v1.0.1), I think there was an error while uploading it. I've been able to install it into a different computer, please try again...

**Comment by jayvdb** [comment]
Still not working, but #21 is probably the cause

**Pull request merged**
